FROM pytorch/pytorch:2.4.1-cuda12.1-cudnn9-devel

WORKDIR /work

COPY Code .

# # Create the Hugging Face cache directory
# RUN mkdir -p /root/.cache/huggingface/hub

# # Copy the model into the container
# COPY Model /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-3B-Instruct

RUN apt-get update && apt-get install -y curl

RUN pip install --no-cache-dir vllm fastapi uvicorn 

ENV TRANSFORMERS_OFFLINE=1
ENV HF_DATASET_OFFLINE=1
# ENV MODEL_PATH=/root/.cache/huggingface/hub/models--Qwen--Qwen2.5-3B-Instruct


EXPOSE 8000

ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000","--reload"]